### ISSUE TITLE
Possible modifications

### ISSUE THREAD

**Issue by roniemartinez** [bibekad123/automation-report#1]
I was looking for a way to create a report and tried this project. This is a great tool!

I just have a few comments:
1. **Make the title customizable**. Probably changing Automation Report to a name of the tool that generated it and add a few things like logo. We can move the project links or credits to the footer of the page.
2. **Support test suites**. Test suites are common to group tests together.
3. **Long texts does not wrap on small screens**.  Just noticed when I add a long non-breaking string like a URL, the tables extend outside of the screen.
4. **Smaller font**.  When there are lots of tests being performed, it seems that only a few is visible on the screen. This can be customizable.

Cheers!

**Comment by bibekad123** [comment]
Hello @roniemartinez , 

Thank you for the comments. Except for your 2nd point, all have been completed on the latest release. 
And for that point, It will be tracked on #2 . 


Please update the package from pip and find the latest changes.

Thank you!
